version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - CLOUD_STORAGE_URL=${CLOUD_STORAGE_URL}
